# Generated by Django 5.0.3 on 2025-06-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_productgalary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgalary',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'productgallery'},
        ),
        migrations.AddField(
            model_name='product',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
