# Generated by Django 5.0.3 on 2025-07-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_variation_variation_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Variation', 'verbose_name_plural': 'Variations'},
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='variation_category',
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
