# Generated by Django 5.0.3 on 2025-07-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_variation_variation_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={},
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('size', 'size'), ('color', 'color')], default='size', max_length=100),
        ),
        migrations.AlterField(
            model_name='variation',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
