# Generated by Django 5.0.3 on 2025-05-31 12:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
