# Generated by Django 5.0.3 on 2025-06-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderproduct_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='tax',
            field=models.FloatField(default=0.0),
        ),
    ]
